const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 const units=()=>page.evaluate(()=>JSON.parse(JSON.stringify({production:BlueprintDefense.game.production,towers:BlueprintDefense.game.towers,dp:BlueprintDefense.game.dp,warehouse:BlueprintDefense.game.warehouse,warehouseLine:BlueprintDefense.game.warehouseLine})));
 async function point(x,y){return page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:p.x+r.x,y:p.y+r.y};},{x,y});}
 async function cell(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
 async function box(a,b,shift=false,release=true){if(shift)await page.keyboard.down('Shift');const p=await point(...a),q=await point(...b);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:10});if(release)await page.mouse.up();if(shift)await page.keyboard.up('Shift');await page.waitForTimeout(100);}
 // Touch events can return before the scheduled toolbar refresh; wait for the observable UI state.
 async function count(n){await page.waitForFunction(n=>document.getElementById('bulkCount').textContent===`已选 ${n} 台`,n,{timeout:5000});await page.locator('#bulkToolbar').waitFor({state:'visible',timeout:5000});assert.equal(await page.locator('#bulkCount').textContent(),`已选 ${n} 台`);}
 await page.keyboard.press('2');await cell(1,43);await page.keyboard.press('3');await cell(1,40);await page.keyboard.press('4');await cell(1,37);let built=await units();assert.equal(built.production.length,3);assert.equal(built.dp,29);
 await box([0,36],[4,46],true);await count(3);assert.match(await page.locator('#bulkSummary').textContent(),/1,100 折金票/);assert.deepEqual(await units(),built);assert.match(await page.locator('#bulkWarning').textContent(),/机内物料会清空/);checks.push('Shift drag selects the full production line including intersecting footprints, excluding the built-in warehouse, without placing the active build tool');
 await page.keyboard.down('Shift');await cell(2,41);await page.keyboard.up('Shift');await count(2);await page.keyboard.down('Shift');await cell(2,41);await page.keyboard.up('Shift');await count(3);checks.push('Shift click removes and re-adds a single building from a multi-selection');
 await page.keyboard.press('m');let q=await point(34,6);await page.mouse.move(q.x,q.y);await page.waitForTimeout(150);assert(await page.locator('#placementPreview').evaluate(e=>e.classList.contains('invalid')));await cell(34,6);assert.deepEqual(await units(),built);assert.match(await page.locator('#status').textContent(),/整组未移动/);await page.keyboard.press('r');assert.deepEqual(await units(),built);await page.keyboard.press('Escape');await count(3);assert.deepEqual(await units(),built);checks.push('invalid group drops and R do not change original positions or directions, and Escape cancels a held move while retaining selection');
 await page.locator('#bulkMoveBtn').click();q=await point(2,37);await page.mouse.move(q.x,q.y);await page.waitForTimeout(150);assert(!(await page.locator('#placementPreview').evaluate(e=>e.classList.contains('invalid'))));assert.deepEqual(await units(),built);await page.screenshot({path:path.join(root,'reports/bulk_move_preview.png')});await cell(2,37);let moved=await units();assert.equal(moved.dp,built.dp);assert.deepEqual(moved.production.map(p=>({...p,x:p.x-1})),built.production);assert.deepEqual(moved.warehouseLine,built.warehouseLine);await count(3);checks.push('group preview moves only ghosts; confirming an overlapping one-cell translation preserves all three building states, warehouse fixtures and money');
 await page.locator('#bulkDeleteBtn').click();assert.equal((await units()).production.length,0);assert.equal((await units()).dp,40);assert(!(await page.locator('#bulkToolbar').isVisible()));await page.keyboard.press('Delete');assert.equal((await units()).dp,40);checks.push('visible bulk demolition refunds the displayed 1,100 tickets once and clears selection');
 await page.keyboard.press('1');await box([10,24],[14,24]);await page.keyboard.press('7');await cell(16,24);await page.keyboard.press('b');assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');await box([9,23],[18,27]);await count(6);assert.match(await page.locator('#bulkSummary').textContent(),/防御塔 1 · 生产设备 5/);await page.screenshot({path:path.join(root,'reports/bulk_selection.png')});built=await units();
 await page.locator('#hotbarSettings').click();await page.locator('#hotbarSearch').fill('传送带');await page.keyboard.press('Backspace');assert.deepEqual(await units(),built);await page.locator('#closeHotbar').click();await page.locator('#board').focus();await page.keyboard.press('Backspace');assert(await page.locator('#bulkDeleteDialog').evaluate(e=>e.open));assert.deepEqual(await units(),built);await page.locator('#confirmBulkDelete').click();assert.equal((await units()).production.length,0);assert.equal((await units()).towers.length,0);assert.equal((await units()).dp,35.5);checks.push('B box-selects a mixed tower/belt group; Backspace edits text inside a dialog safely, then removes the group with the proper 50% tower refund');
 await page.keyboard.press('7');await cell(12,22);await page.keyboard.press('Escape');await cell(12,22);await page.keyboard.down('Shift');await cell(12,22);await page.keyboard.up('Shift');assert(!(await page.locator('#bulkToolbar').isVisible()));await page.keyboard.down('Shift');await cell(12,22);await page.keyboard.up('Shift');await count(1);await page.keyboard.press('Escape');assert(!(await page.locator('#bulkToolbar').isVisible()));checks.push('Shift click can toggle an existing single selection and Escape clears selection without demolishing');
 await page.keyboard.press('b');await box([11,21],[14,25],false,false);await page.keyboard.press('Escape');await page.mouse.up();assert(!(await page.locator('#bulkToolbar').isVisible()));assert.equal((await units()).towers.length,1);checks.push('Escape during an unfinished selection drag cancels cleanly without a delayed selection or deployment');
 await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();await page.keyboard.press('b');await box([11,21],[14,25]);await count(1);await page.locator('#bulkClearBtn').click();await page.keyboard.press('Escape');const before=await page.evaluate(()=>BlueprintDefense.camera.cx);q=await point(22,22);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+60,q.y+30,{steps:5});await page.mouse.up();assert.notEqual(await page.evaluate(()=>BlueprintDefense.camera.cx),before);checks.push('box selection uses camera coordinates after zoom, and ordinary left dragging still pans outside box mode');
 await page.setViewportSize({width:390,height:844});await page.locator('#zoomReset').click();await page.locator('#boxSelectBtn').click();const cdp=await page.context().newCDPSession(page),r=await page.locator('#board').boundingBox(),cx=r.x+r.width/2,cy=r.y+r.height/2;built=await units();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-20,y:cy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-10,y:cy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-10,y:cy,id:1},{x:cx+20,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-50,y:cy,id:1},{x:cx+50,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await units(),built);await count(0);assert(await page.evaluate(()=>BlueprintDefense.camera.zoom>1));
 await page.locator('#zoomReset').click();await box([11,21],[14,25]);await count(1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(root,'reports/bulk_phone.png')});await page.locator('#bulkDeleteBtn').click();assert.equal((await units()).towers.length,0);checks.push('phone pinch cancels an active box draft; the responsive toolbar fits and supports demolition without a keyboard');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors};await fs.writeFile(path.join(root,'reports/bulk_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
