const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 async function cell(x,y){const p=await page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:p.x+r.x,y:p.y+r.y};},{x,y});await page.mouse.click(p.x,p.y);}
 assert.equal(await page.locator('#dp').textContent(),'4,000');assert.match(await page.locator('[data-type="0"] .cost').textContent(),/折金票900/);assert.match(await page.locator('[data-type="8"]').getAttribute('title'),/4,800 折金票/);
 await page.keyboard.press('7');await cell(6,5);assert.equal(await page.locator('#dp').textContent(),'3,100');assert.match(await page.locator('#status').textContent(),/900 折金票/);await cell(7,6);assert.match(await page.locator('#withdrawBtn').textContent(),/450 折金票/);assert.match(await page.locator('#upgradeBtn').textContent(),/1,400 折金票/);assert.match(await page.locator('#upgradeRequirement').textContent(),/76 → 228/);await page.locator('#withdrawBtn').click();assert.equal(await page.locator('#dp').textContent(),'3,550');checks.push('starting money, tower prices, upgrades, spending and precise 50% refund all use tickets at 100x');
 await page.locator('#techBtn').click();await page.locator('[data-research-tab="combat"]').click();assert.match(await page.locator('[data-research="ballistics"] .tech-cost').textContent(),/2,200 折金票.*15 秒/);assert.match(await page.locator('[data-research="ballistics"] .tech-cost').textContent(),/外壳 ×8/);assert.match(await page.locator('[data-research="logistics"] p').textContent(),/9,900.*20,000/);assert.match(await page.locator('#techStatus').textContent(),/3,550 \/ 9,900/);await page.screenshot({path:path.join(root,'reports/v12_ticket_technology.png')});await page.locator('#closeTech').click();checks.push('research prices and capacity scale while material counts and durations do not');
 await page.locator('[data-deck-page="2"]').click();await page.locator('[data-production-type="3"]').click();await cell(1,19);await cell(2,20);assert.equal(await page.locator('#detailDamage').textContent(),'400');assert.match(await page.locator('#recipePreview').textContent(),/晶体外壳 → 200 折金票/);assert.match(await page.locator('#recipePreview').textContent(),/铁制零件 → 500 折金票/);assert.match(await page.locator('#productionOption').textContent(),/折金票/);
 // One buffered-product fixture isolates display settlement; actual production is
 // separately exercised by the real UI play and current campaign suites.
 await page.evaluate(()=>{const g=BlueprintDefense.game,p=g.production[0];p.cargo={kind:'item_crystal_shell',age:1};g.updateProduction(.05);BlueprintDefense.updateUI();});assert.equal(await page.locator('#dp').textContent(),'3,350');assert.match(await page.locator('#productionIncome').textContent(),/200/);assert.match(await page.locator('#towerRecord').textContent(),/供应 200 折金票/);checks.push('production construction, item values, received income and cumulative income share the currency formatter');
 await page.locator('#scenario').selectOption('boss');assert.equal(await page.locator('#dp').textContent(),'50,000');assert.match(await page.locator('#productionUnlock').textContent(),/已解锁/);
 const layouts=[];for(const [width,height] of [[1920,1080],[1540,1060],[1280,720],[1000,800],[780,1000],[560,844],[390,844]]){
  await page.setViewportSize({width,height});await page.waitForTimeout(100);const layout=await page.evaluate(()=>{const d=document.getElementById('dp'),r=d.getBoundingClientRect(),p=d.parentElement.getBoundingClientRect();return {width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,moneyOverflow:d.scrollWidth>d.clientWidth+1,right:r.right,parentRight:p.right};});assert(!layout.overflow&&!layout.moneyOverflow,JSON.stringify(layout));layouts.push(layout);if([1540,390].includes(width))await page.screenshot({path:path.join(root,`reports/v12_tickets_${width}.png`)});
 }checks.push('50,000-ticket balances and equipment prices fit seven desktop and phone viewports');
 const ui=await page.evaluate(()=>document.body.innerText+'\n'+[...document.querySelectorAll('dialog')].map(e=>e.textContent).join('\n')+'\n'+[...document.querySelectorAll('[title],[aria-label]')].map(e=>(e.title||'')+(e.getAttribute('aria-label')||'')).join('\n'));assert(!/\bDP\b/.test(ui));assert.deepEqual(errors,[]);
 checks.push('current UI, dialogs, tooltips and accessible labels contain no leftover DP currency');
 const report={passed:checks.length,checks,layouts,errors};await fs.writeFile(path.join(root,'reports/currency_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
