const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {starterPlan}=require('./geometry_helpers.cjs'),{makePlanner}=require('./economy_campaign.cjs');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/offline/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 async function cell(x,y){const p=await page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:r.x+p.x,y:r.y+p.y};},{x,y});await page.mouse.click(p.x,p.y);}
 await page.locator('#techBtn').click();await page.locator('[data-research-tab="combat"]').click();assert.equal(await page.locator('.tech-node').count(),15);assert(await page.locator('[data-start-research="ballistics"]').isDisabled());assert.match(await page.locator('[data-research="ballistics"] .tech-state').textContent(),/不足/);await page.screenshot({path:path.join(root,'reports/v12_technology.png')});await page.locator('#closeTech').click();checks.push('fifteen research nodes show prerequisites, real inventory and unmet costs from a fresh run');
 // All actions until the simulation section below are real UI interactions and RAF time.
 for(const [type,x,y,dir] of starterPlan){await page.locator(`[data-deck-page="${type===0?3:2}"]`).click();await page.locator(`[data-production-type="${type}"]`).click();for(let n=0;n<4;n++){const direction=await page.locator('#rotateBtn').textContent();if(direction.includes('向上'))break;await page.keyboard.press('r');}await cell(x,y);}
 await cell(1,35);await page.locator('#productionOption').selectOption('balanced');assert.match(await page.locator('#productionOptionHint').textContent(),/只|不会/);
 for(const [x,y] of [[6,5],[9,7],[17,5]]){await page.keyboard.press('7');await cell(x,y);}assert.equal(await page.evaluate(()=>BlueprintDefense.game.towers.length),3);assert.equal(await page.locator('#dp').textContent(),'0');
 await page.locator('#startBtn').click();await page.locator('#speedBtn').click();
 await page.waitForFunction(()=>BlueprintDefense.game.warehouseCount('item_crystal_shell')>=8&&BlueprintDefense.game.dp>=22,{},{timeout:55000});
 await page.locator('#startBtn').click();assert.equal(await page.evaluate(()=>BlueprintDefense.game.phase),'paused');const stock=await page.evaluate(()=>BlueprintDefense.game.warehouseCount('item_crystal_shell'));
 await page.locator('#techBtn').click();await page.locator('[data-research-tab="combat"]').click();await page.locator('[data-start-research="ballistics"]').click();assert.equal(await page.evaluate(()=>BlueprintDefense.game.warehouseCount('item_crystal_shell')),stock-8);assert.match(await page.locator('[data-start-research="ballistics"]').textContent(),/暂停/);await page.locator('#closeTech').click();await page.locator('#startBtn').click();
 await page.waitForFunction(()=>BlueprintDefense.game.researched.includes('ballistics')&&BlueprintDefense.game.warehouseCount('item_crystal_shell')>=4&&BlueprintDefense.game.dp>=14,{},{timeout:35000});await page.locator('#startBtn').click();
 const played=await page.evaluate(()=>({time:BlueprintDefense.game.time,wave:BlueprintDefense.game.wave+1,life:BlueprintDefense.game.life,kills:BlueprintDefense.game.kills,stock:BlueprintDefense.game.warehouse,dp:BlueprintDefense.game.dp}));assert(played.life>0);console.log('UI play',JSON.stringify(played));
 await cell(17,5);assert(await page.locator('#upgradeBtn').isEnabled());await page.locator('#upgradeBtn').click();assert.match(await page.locator('#detailName').textContent(),/扩装/);assert.match(await page.locator('#supplyDetail').textContent(),/弹药/);assert.match(await page.locator('#deploymentCount').textContent(),/不限量/);await page.screenshot({path:path.join(root,'reports/v12_play_research.png')});checks.push('real UI builds a 1,300-ticket line and three towers, produces research stock, pauses, researches, resumes and refits without resource grants or clock stepping');
 await page.locator('#techBtn').click();await page.locator('[data-research-tab="combat"]').click();await page.screenshot({path:path.join(root,'reports/v12_technology_researched.png')});await page.locator('#closeTech').click();
 for(const viewport of [{width:1920,height:1080},{width:1280,height:720},{width:390,height:844}]){await page.setViewportSize(viewport);await page.locator('#techBtn').click();await page.locator('[data-research-tab="combat"]').click();assert(await page.locator('#closeTech').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#techDialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:path.join(root,`reports/v12_tech_${viewport.width}.png`)});await page.locator('#closeTech').click();}checks.push('research and inventory panels fit desktop, laptop and phone widths');
 await page.setViewportSize({width:1540,height:1060});await page.locator('#resetBtn').click();assert.deepEqual(await page.evaluate(()=>BlueprintDefense.game.researched),[]);assert.deepEqual(await page.evaluate(()=>BlueprintDefense.game.warehouse),{});checks.push('reset clears research, job, material stock and card locks');
 await page.locator('#resetBtn').click();await page.locator('#scenario').selectOption('boss');await page.keyboard.press('9');await cell(23,6);await cell(24,7);await page.locator('#upgradeBtn').click();assert.equal(await page.locator('#detailName').textContent(),'维什戴尔改件');assert.equal(await page.locator('#detailDamage').textContent(),'33000');assert(!/彩蛋|娱乐|氦气/.test(await page.locator('#detailDesc').textContent()));checks.push('explicitly provisioned Rodin practice preserves the animated, voiced heavy mortar refit');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors,played};await fs.writeFile(path.join(root,'reports/economy_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
