const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),{starterPlan,campaignPlan}=require('./geometry_helpers.cjs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/offline/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 async function point(x,y){return page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:r.x+p.x,y:r.y+p.y};},{x,y});}
 async function cell(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
 async function type(n){await page.locator(`[data-deck-page="${[0,8].includes(n)?3:2}"]`).click();await page.locator(`[data-production-type="${n}"]`).click();}
 assert.match(await page.locator('.blueprint-size b').textContent(),/64 × 48/);assert.equal(await page.evaluate(()=>BlueprintDefense.camera.width),64);assert.equal(await page.evaluate(()=>BlueprintDefense.sound.worldWidth),64);
 await cell(40,12);assert.equal(await page.locator('#detailName').textContent(),'协议核心');assert.equal(await page.locator('#detailRange').textContent(),'9×9');assert(await page.locator('#towerActions').isHidden());assert(await page.locator('#rotateBtn').isHidden());await page.locator('#detailImage').evaluate(x=>x.decode());await page.screenshot({path:path.join(root,'reports/geometry_core.png')});
 checks.push('64x48 map, original 9x9 core and its inspector load; core has no build, rotation or demolition actions');
 await type(0);await cell(40,12);assert.equal(await page.locator('#dp').textContent(),'4,000');assert.equal(await page.locator('#detailName').textContent(),'协议核心');await cell(59,47);assert.match(await page.locator('#detailName').textContent(),/仓库存取线/);assert.match(await page.locator('#detailRole').textContent(),/8×4/);assert(await page.locator('#towerActions').isHidden());
 checks.push('every interior core and warehouse cell is selectable and immutable without spending DP');
 for(const [n,x,y] of starterPlan){await type(n);await cell(x,y);}
 assert.equal(await page.locator('#dp').textContent(),'2,700');assert.equal(await page.evaluate(()=>BlueprintDefense.game.production.length),5);await cell(3,41);assert.equal(await page.locator('#detailName').textContent(),'精炼炉');assert.match(await page.locator('#detailRole').textContent(),/3×3/);assert.equal(await page.locator('#productionOption').inputValue(),'furnance_crystal_shell_1');
 const dimensions=await page.evaluate(()=>{const g=BlueprintDefense.game,result=[];for(let type=0;type<DATA.production.types.length;type++){const def=DATA.production.types[type];if(!def.faces)continue;for(let dir=0;dir<4;dir++){const img=new Image();img.src=def.faces[dir];result.push({type,dir,src:def.faces[dir],foot:g.productionFootprint(type,dir)});}}return result;});
 for(const d of dimensions){const ratio=await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();return img.naturalWidth/img.naturalHeight;},d.src);assert.equal(ratio,d.foot.width/d.foot.depth);}
 await page.screenshot({path:path.join(root,'reports/geometry_production.png')});checks.push('mouse-built 13-DP line uses full-size art and real ports; all directional images match occupied rectangles');
 await page.locator('#rotateBtn').click();assert.match(await page.locator('#detailRange').textContent(),/左 \/ 右/);await page.locator('#startBtn').click();await page.evaluate(()=>{BlueprintDefense.game.advance(10);BlueprintDefense.game.togglePause();BlueprintDefense.updateUI();});await cell(3,41);assert.match(await page.locator('#productionState').textContent(),/入口朝向不匹配/);assert.equal(await page.evaluate(()=>BlueprintDefense.game.productionEarned),0);
 for(let i=0;i<3;i++)await page.locator('#rotateBtn').click();await page.evaluate(()=>{const g=BlueprintDefense.game;g.togglePause();g.advance(9);g.togglePause();BlueprintDefense.updateUI();});assert(await page.evaluate(()=>BlueprintDefense.game.productionEarned>=4));const time=await page.evaluate(()=>BlueprintDefense.game.time);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>BlueprintDefense.game.time),time);
 checks.push('actual incorrectly rotated 3x3 refinery blocks cargo; rotating it back resumes real DP income, and pause freezes production');
 await page.locator('#resetBtn').click();await type(0);await cell(12,20);await type(1);await cell(12,22);await cell(14,20);assert.match(await page.locator('#detailRole').textContent(),/3×1/);await page.locator('#rotateBtn').click();assert.match(await page.locator('#status').textContent(),/重叠/);assert.match(await page.locator('#detailRole').textContent(),/3×1/);
 await cell(12,22);await page.locator('#withdrawBtn').click();await cell(14,20);await page.locator('#rotateBtn').click();assert.match(await page.locator('#detailRole').textContent(),/1×3/);await cell(12,22);assert.equal(await page.locator('#detailName').textContent(),'仓库取货口');
 checks.push('rotation preview and committed occupancy agree for rectangular ports; blocked rotation keeps the old orientation and every new interior cell selects it');
 await page.locator('#resetBtn').click();await type(2);await cell(19,6);assert.equal(await page.evaluate(()=>BlueprintDefense.game.production.length),0);assert.match(await page.locator('#status').textContent(),/通道/);
 await page.keyboard.press('Escape');const anchor=await point(13,21);await page.mouse.move(anchor.x,anchor.y);await page.mouse.wheel(0,-500);await type(2);await cell(12,20);await cell(14,22);assert.equal(await page.locator('#detailName').textContent(),'精炼炉');assert.equal(await page.evaluate(()=>BlueprintDefense.game.productionAt(14,22).type),2);await page.locator('#zoomReset').click();await page.screenshot({path:path.join(root,'reports/geometry_zoom.png')});
 checks.push('a footprint crossing the route is rejected; zoomed mouse deployment and non-anchor selection use expanded map coordinates');
 await page.locator('#resetBtn').click();await page.locator('#scenario').selectOption('boss');await page.keyboard.press('9');await cell(22,17);await cell(24,19);await page.locator('#upgradeBtn').click();assert.equal(await page.locator('#detailName').textContent(),'维什戴尔改件');assert.equal(await page.locator('#detailDamage').textContent(),'33000');assert(!/彩蛋|娱乐|氦气/.test(await page.locator('#detailDesc').textContent()));assert.equal(await page.evaluate(()=>BlueprintDefense.actors.images.size),11);
 await page.setViewportSize({width:390,height:844});await page.locator('#zoomReset').click();await cell(24,19);assert.equal(await page.locator('#detailName').textContent(),'维什戴尔改件');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await cell(40,12);assert.equal(await page.locator('#detailName').textContent(),'协议核心');await page.screenshot({path:path.join(root,'reports/geometry_phone.png')});await page.locator('#helpBtn').click();assert(!/压缩为 1 格/.test(await page.locator('#help').textContent()));await page.locator('#closeHelp').click();
 checks.push('upgraded animated mortar remains usable; phone layout can select the large core and buildings, and help describes original dimensions');
 assert.deepEqual(errors,[]);const result={passed:checks.length,checks,errors};await fs.writeFile(path.join(root,'reports/geometry_browser_checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
