const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/offline/blueprint_defense.html')).href;
 await page.goto(url);await page.evaluate(()=>BlueprintDefense.ready);
 async function startFreshAfterReload(){await page.evaluate(()=>BlueprintDefense.session.ready);if(await page.locator('#mainMenu').evaluate(e=>e.open)){await page.locator('#menuNew').click();if(await page.locator('#sessionConfirm').evaluate(e=>e.open))await page.locator('#sessionConfirmOK').click();}}
 const snapshot=()=>page.evaluate(()=>({dp:BlueprintDefense.game.dp,units:BlueprintDefense.game.production.map(p=>({type:p.type,x:p.x,y:p.y,dir:p.dir,recipe:p.recipe,source:p.source,deliveryMode:p.deliveryMode})),towers:BlueprintDefense.game.towers.length}));
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('blueprint-defense.hotbar.v1')));
 async function cell(x,y){const p=await page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:r.x+p.x,y:r.y+p.y};},{x,y});await page.mouse.click(p.x,p.y);}
 async function config(slot,id,option,dir){await page.locator(`[data-hotbar-slot="${slot}"]`).click({button:'right'});await page.locator(`[data-hotbar-device="${id}"]`).click();if(option)await page.locator('#hotbarOption').selectOption(option);if(dir!=null)await page.locator('#hotbarDirection').selectOption(String(dir));await page.locator('#hotbarSave').click();}
 assert.equal(await page.locator('[data-hotbar-slot]').count(),9);
 await page.keyboard.press('2');await cell(1,43);await page.keyboard.press('3');await cell(1,40);await page.keyboard.press('4');await cell(1,37);
 let state=await snapshot();assert.deepEqual(state.units.map(p=>[p.type,p.x,p.y,p.dir]),[[0,1,43,3],[2,1,40,3],[3,1,37,3]]);assert.equal(state.dp,29);
 for(const p of [[6,5],[9,7],[17,5]]){await page.keyboard.press('7');await cell(...p);}assert.equal((await snapshot()).dp,2);
 await page.screenshot({path:path.join(root,'reports/hotbar_default_line.png')});checks.push('default 1–9 bar builds a connected source/refinery/storage line and three guns using only keys and grid clicks; real costs and footprints apply');
 await page.locator('#resetBtn').click();
 await config(4,'furnance_1','furnance_quartz_glass_1',0);await page.keyboard.press('5');assert.equal(await page.locator('#productionOption').inputValue(),'furnance_quartz_glass_1');await cell(13,24);await cell(17,24);
 await config(5,'furnance_1','furnance_crystal_shell_1',2);await page.keyboard.press('6');await cell(23,24);
 state=await snapshot();assert.deepEqual(state.units.map(p=>[p.recipe,p.dir]),[['furnance_quartz_glass_1',0],['furnance_quartz_glass_1',0],['furnance_crystal_shell_1',2]]);checks.push('two slots for the same machine independently retain recipes and directions; repeated placement keeps the chosen preset');
 await cell(14,25);await page.keyboard.press('Shift+Digit8');let slots=await saved();assert.deepEqual(slots[7],{id:'furnance_1',option:'furnance_quartz_glass_1',dir:0});await page.keyboard.press('8');await cell(28,24);assert.equal((await snapshot()).units.at(-1).recipe,'furnance_quartz_glass_1');
 await page.locator('[data-hotbar-slot="3"]').click({button:'right'});await page.locator('#hotbarUseCurrent').click();await page.locator('#hotbarSave').click();assert.deepEqual((await saved())[3],slots[7]);checks.push('Shift + digit and Use current capture actual selected or held machine settings without modifying the original');
 await config(4,'furnance_1','furnance_iron_nugget_1',3);await page.keyboard.press('5');const before=await snapshot();await cell(9,21);assert.deepEqual(await snapshot(),before);assert.match(await page.locator('#status').textContent(),/蓝铁冶炼/);
 await page.keyboard.press('9');await cell(2,17);assert.deepEqual(await snapshot(),before);assert.match(await page.locator('#status').textContent(),/研究|科技/);checks.push('stored blue-iron recipes and advanced towers do not bypass unlocks, research, materials or payment; invalid placement leaves no building');
 await page.locator('[data-hotbar-slot="0"]').click({button:'right'});await page.locator('#hotbarClear').click();assert.equal((await saved())[0],null);await page.keyboard.press('1');assert(await page.locator('#hotbarDialog').evaluate(e=>e.open));
 await page.locator('#hotbarSearch').fill('紫晶');assert(await page.locator('[data-hotbar-device="furnance_1"]').isVisible());assert(!(await page.locator('[data-hotbar-device="battle_turret_1"]').isVisible()));await page.locator('#hotbarSearch').fill('zz-no-machine');assert(await page.locator('#hotbarNoResults').isVisible());await page.keyboard.press('Escape');assert.equal((await saved())[0],null);
 slots=await saved();await page.reload();await page.evaluate(()=>BlueprintDefense.ready);await startFreshAfterReload();assert.deepEqual(await saved(),slots);assert.equal((await snapshot()).units.length,0);await page.locator('#resetBtn').click();assert.deepEqual(await saved(),slots);await page.keyboard.press('8');assert.equal(await page.locator('#productionOption').inputValue(),'furnance_quartz_glass_1');checks.push('empty slots open configuration; search matches recipe products; Escape discards drafts; saved presets survive reload and new games independently of run progress');
 await page.locator('#startBtn').click();await page.waitForTimeout(600);await page.locator('#hotbarSettings').click();assert.equal(await page.evaluate(()=>BlueprintDefense.game.phase),'paused');const time=await page.evaluate(()=>BlueprintDefense.game.time);await page.locator('#hotbarSearch').fill('9');await page.keyboard.press('Space');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>BlueprintDefense.game.time),time);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>BlueprintDefense.game.phase),'paused');checks.push('opening configuration pauses battle, form typing never triggers build/pause shortcuts, and closing leaves the user in control of resuming');
 await page.locator('#hotbarSettings').click();await page.locator('#hotbarDefaults').click();await page.locator('#closeHotbar').click();await page.locator('#resetBtn').click();
 for(const width of [390,320,768,1024,1540]){await page.setViewportSize({width,height:width<800?844:1060});await page.waitForTimeout(100);const bounds=await page.locator('[data-hotbar-slot]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,right:r.right,y:r.y,bottom:r.bottom};}));assert(bounds.every(r=>r.x>=0&&r.right<=width));const board=await page.locator('#board').boundingBox();assert(bounds.every(r=>r.y>=board.y+board.height));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:390,height:844});await page.locator('[data-hotbar-slot="2"]').click();assert.match(await page.locator('#detailName').textContent(),/精炼/);await page.screenshot({path:path.join(root,'reports/hotbar_phone.png')});await page.locator('#hotbarSettings').click();await page.locator('[data-edit-slot="8"]').click();await page.locator('[data-hotbar-device="loader_1"]').click();await page.locator('#hotbarDirection').selectOption('1');await page.locator('#hotbarSave').click();assert.equal((await saved())[8].id,'loader_1');checks.push('all nine slots fit 320–1540 px screens, sit below rather than cover the canvas, and support phone-sized tap configuration');
 await page.setViewportSize({width:1540,height:1060});await page.locator('#hotbarSettings').click();await page.locator('[data-edit-slot="2"]').click();await page.waitForTimeout(200);await page.screenshot({path:path.join(root,'reports/hotbar_configuration.png')});await page.locator('#closeHotbar').click();
 await page.evaluate(()=>localStorage.setItem('blueprint-defense.hotbar.v1',JSON.stringify([{id:'missing-device'},null,{id:'log_hongs_bus'}, {id:'furnance_1',option:'wrong',dir:99},null,null,null,null,null])));await page.reload();await page.evaluate(()=>BlueprintDefense.ready);await startFreshAfterReload();await page.keyboard.press('4');assert.equal(await page.locator('#productionOption').inputValue(),'furnance_crystal_shell_1');assert.match(await page.locator('#rotateBtn').textContent(),/向右/);await page.keyboard.press('1');assert(await page.locator('#hotbarDialog').evaluate(e=>e.open));await page.keyboard.press('Escape');await page.evaluate(()=>localStorage.setItem('blueprint-defense.hotbar.v1','broken'));await page.reload();await page.evaluate(()=>BlueprintDefense.ready);await startFreshAfterReload();await page.keyboard.press('7');assert.match(await page.locator('#detailName').textContent(),/铳械/);checks.push('obsolete device IDs, built-in warehouse entries, invalid options/directions and malformed saved JSON are safely normalized or reset');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors};await fs.writeFile(path.join(root,'reports/hotbar_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
