const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),errors=[],checks=[];page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 async function cell(x,y){y+=16;const p=await page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:r.x+p.x,y:r.y+p.y};},{x,y});await page.mouse.click(p.x,p.y);}
 async function machine(type,x,y,option){await page.locator(`[data-deck-page="${type===0?3:2}"]`).click();await page.locator(`[data-production-type="${type}"]`).click();if(option)await page.locator('#productionOption').selectOption(option);for(let i=0;i<4;i++){if((await page.locator('#rotateBtn').innerText()).includes('向上'))break;await page.keyboard.press('r');}await cell(x,y);}
 await page.locator('#techBtn').click();assert.equal(await page.locator('[data-research-tab="production"] small').innerText(),'07');assert.equal(await page.locator('[data-research-tab="combat"] small').innerText(),'08');assert.equal(await page.locator('.tech-node:visible').count(),7);assert.equal(await page.locator('.tech-branch:visible').count(),3);assert(await page.locator('[data-start-research="densification"]').isDisabled());
 await page.screenshot({path:path.join(root,'reports/industrial_technology.png')});await page.locator('[data-research-tab="combat"]').click();assert.equal(await page.locator('.tech-node:visible').count(),8);assert.match(await page.locator('[data-research="storm"] .tech-parent').textContent(),/致密冶炼/);assert.match(await page.locator('[data-research="precision"] .tech-cost').textContent(),/高容谷地电池/);
 for(const width of [390,768,1540]){await page.setViewportSize({width,height:1060});await page.locator('[data-research-tab="production"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#techDialog .dialog-body').evaluate(e=>e.scrollWidth<=e.clientWidth+1));}
 checks.push('seven production and eight combat technologies share responsive tabs; advanced refits expose their new material prerequisites');
 await page.locator('[data-research="densification"] .tech-machine').click();assert.match(await page.locator('#detailName').innerText(),/研磨机/);const money=await page.locator('#dp').innerText();await cell(1,23);assert.equal(await page.locator('#dp').innerText(),money);assert.match(await page.locator('#status').innerText(),/需要研究/);checks.push('view-machine links open the actual inspector and locked placement neither spends nor creates a machine');
 await page.locator('#scenario').selectOption('boss');
 await machine(0,1,27,'item_iron_powder');await machine(9,1,23,'thickener_iron_enr_powder_1');await machine(2,1,20,'furnance_iron_enr_1');await machine(3,1,17,'warehouse');
 await page.locator('#startBtn').click();await page.locator('#speedBtn').click();await page.waitForTimeout(4200);await page.locator('#startBtn').click();await cell(2,24);assert.match(await page.locator('#productionState').innerText(),/砂叶粉末 0\/1/);assert.match(await page.locator('#recipePreview').innerText(),/蓝铁粉末 ×2/);assert.match(await page.locator('#recipePreview').innerText(),/砂叶粉末 ×1/);
 await machine(0,4,27,'item_plant_moss_powder_3');await page.locator('#startBtn').click();await page.waitForFunction(()=>BlueprintDefense.game.warehouseCount('item_iron_enr')>60,{},{timeout:14000});await page.locator('#startBtn').click();
 const result=await page.evaluate(()=>({phase:BlueprintDefense.game.phase,steel:BlueprintDefense.game.warehouseCount('item_iron_enr'),units:BlueprintDefense.game.production.map(p=>({type:p.type,x:p.x,y:p.y,dir:p.dir})),time:BlueprintDefense.game.time}));assert(result.steel>60);assert.equal(result.units.length,5);await cell(2,24);await page.screenshot({path:path.join(root,'reports/industrial_dual_input.png')});checks.push('in explicitly provisioned practice, real UI and RAF time show missing second input, then two warehouse lanes produce and store new steel through the real 6×4 grinder and refinery');
 await page.locator('#hotbarSettings').click();await page.locator('#hotbarSearch').fill('高容谷地电池');assert(await page.locator('[data-hotbar-device="tools_assebling_mc_1"]').isVisible());await page.locator('[data-hotbar-device="tools_assebling_mc_1"]').click();await page.locator('#hotbarOption').selectOption('tools_proc_battery_3_1');await page.locator('#hotbarDirection').selectOption('3');await page.locator('#hotbarSave').click();await page.keyboard.press('1');assert.match(await page.locator('#recipePreview').innerText(),/钢制零件 ×10/);assert.match(await page.locator('#recipePreview').innerText(),/致密源石粉末 ×15/);assert.match(await page.locator('#recipePreview').innerText(),/10s/);await page.screenshot({path:path.join(root,'reports/industrial_battery_recipe.png')});
 await page.locator('#scenario').selectOption('campaign');await page.keyboard.press('1');const before=await page.locator('#dp').innerText();await cell(1,23);assert.equal(await page.locator('#dp').innerText(),before);assert.match(await page.locator('#status').innerText(),/需要研究/);checks.push('new recipe names are searchable and retain complete counts in hotbar presets; a new campaign cannot use a preset to bypass its research');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors,practiceResult:result};await fs.writeFile(path.join(root,'reports/industrial_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
