const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),reference=require('../sources/original_bulk_controls_reference.json');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/offline/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 const state=()=>page.evaluate(()=>JSON.parse(JSON.stringify({p:BlueprintDefense.game.production,t:BlueprintDefense.game.towers,dp:BlueprintDefense.game.dp,warehouse:BlueprintDefense.game.warehouse})));
 async function point(x,y){return page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:r.x+p.x,y:r.y+p.y};},{x,y});}
 async function cell(x,y,button='left'){const p=await point(x,y);await page.mouse.click(p.x,p.y,{button});}
 async function drag(a,b,button='left',release=true){const p=await point(...a),q=await point(...b);await page.mouse.move(p.x,p.y);await page.mouse.down({button});await page.mouse.move(q.x,q.y,{steps:8});if(release)await page.mouse.up({button});await page.waitForTimeout(120);}
 async function count(n){assert.equal(await page.locator('#bulkCount').textContent(),`已选 ${n} 台`);}
 const keys={fac_enter_dismantle_mode:120,fac_exit_batch_select_mode:120,fac_batch_drag_select:323,fac_batch_drag_unselect:324,fac_batch_mode_move:109,fac_batch_mode_del:102};for(const [action,key] of Object.entries(keys))assert.equal(reference.actions[action].primaryKeyboardInput.key,key);checks.push('primary controls match the extracted original default binding data: X, left/right mouse, M and F');
 await page.keyboard.press('1');await drag([10,25],[15,25]);await page.keyboard.press('7');await cell(18,24);const built=await state();assert.equal(built.p.length,6);assert.equal(built.t.length,1);
 await page.keyboard.press('x');assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');await count(0);
 await drag([10,25],[12,25]);await count(3);await drag([13,25],[15,25]);await count(6);await cell(18,24);await count(7);await cell(18,24);await count(6);assert.match(await page.locator('#bulkSize').textContent(),/6 × 1/);assert.deepEqual(await state(),built);checks.push('X enters persistent batch mode; left drags union separate rectangles and plain left clicks toggle single targets');
 await drag([10,25],[12,25],'right',false);await count(3);assert.equal(await page.locator('#bulkToolbar').evaluate(e=>getComputedStyle(e).visibility),'hidden');await page.mouse.up({button:'right'});await count(3);assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');await drag([10,25],[12,25]);await count(6);
 await drag([10,25],[14,25],'right',false);await count(1);let q=await point(12,25);await page.mouse.move(q.x,q.y,{steps:5});await page.waitForTimeout(120);await count(3);await page.mouse.up({button:'right'});await count(3);checks.push('right drag subtracts without exiting; its live result is recomputed from the initial selection when the rectangle shrinks');
 await drag([10,25],[12,25]);await count(6);await page.locator('#bulkReverseBtn').click();await drag([10,25],[11,25]);await count(4);await page.locator('#bulkReverseBtn').click();await drag([10,25],[11,25]);await count(6);checks.push('the visible reverse toggle supports the same subtraction operation on touch devices');
 await page.keyboard.press('m');await cell(20,8);assert.deepEqual(await state(),built);assert.match(await page.locator('#status').textContent(),/整组未移动/);await cell(25,25,'right');await count(6);assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');assert.deepEqual(await state(),built);checks.push('M previews an atomic move; a blocked drop changes nothing and right-click returns to the original batch selection');
 q=await point(12,25);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.waitForTimeout(600);assert.match(await page.locator('#bulkMoveBtn').textContent(),/移动中/);assert.deepEqual(await state(),built);await page.mouse.up();q=await point(12,27);await page.mouse.move(q.x,q.y);await page.waitForTimeout(120);assert(!(await page.locator('#placementPreview').evaluate(e=>e.classList.contains('invalid'))));await cell(12,27);let moved=await state();assert.deepEqual(moved.p.map(p=>({...p,y:p.y-2})),built.p);assert.equal(moved.dp,built.dp);assert.deepEqual(moved.t,built.t);await count(6);assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');checks.push('holding left mouse picks up the group without toggling a member; release does not drop, the grab offset is preserved, and click confirms into batch mode');
 await page.screenshot({path:path.join(root,'reports/original_bulk_selection.png')});
 q=await point(12,27);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.waitForTimeout(100);await page.keyboard.press('Escape');await page.waitForTimeout(500);await page.mouse.up();assert(!(await page.locator('#bulkToolbar').isVisible()));assert.deepEqual(await state(),moved);checks.push('Escape cancels a pending long press and cannot produce a delayed pickup');
 await page.keyboard.press('x');await drag([10,27],[15,27]);await count(6);await page.keyboard.press('f');assert(await page.locator('#bulkDeleteDialog').evaluate(e=>e.open));assert.deepEqual(await state(),moved);assert.match(await page.locator('#bulkDeleteRefund').textContent(),/600 折金票/);await page.screenshot({path:path.join(root,'reports/original_bulk_confirm.png')});await page.keyboard.press('f');assert.deepEqual(await state(),moved);await page.keyboard.press('Escape');assert.deepEqual(await state(),moved);await count(6);checks.push('F opens an in-game confirmation for at least five objects; repeated F cannot confirm it and Escape retains buildings and selection');
 await drag([15,27],[16,27],'right');await count(5);await page.keyboard.press('f');assert(await page.locator('#bulkDeleteDialog').evaluate(e=>e.open));await page.locator('#cancelBulkDelete').click();await drag([14,27],[16,27],'right');await count(4);await page.keyboard.press('f');assert(!(await page.locator('#bulkDeleteDialog').evaluate(e=>e.open)));await count(0);assert.equal((await state()).p.length,2);assert.equal((await state()).dp,moved.dp+4);assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'true');checks.push('the original threshold is exact: five asks, four dismantles directly, refunds once and leaves batch mode active');
 await drag([14,27],[15,27]);await cell(18,24);await count(3);await page.keyboard.press('f');assert.equal((await state()).p.length,0);assert.equal((await state()).t.length,0);assert.equal((await state()).dp,35.5);
 await page.keyboard.press('x');await page.keyboard.press('1');await drag([10,25],[14,25]);await page.keyboard.press('x');await drag([10,25],[14,25]);await page.keyboard.press('f');const beforeConfirm=await state();await page.locator('#confirmBulkDelete').click();assert.equal((await state()).p.length,0);assert.equal((await state()).dp,beforeConfirm.dp+5);await page.keyboard.press('f');assert.equal((await state()).dp,beforeConfirm.dp+5);checks.push('confirmation dismantles the captured selection once and never manufactures inventory or excess refunds');
 await page.keyboard.press('x');assert(!(await page.locator('#bulkToolbar').isVisible()));await page.keyboard.press('x');await cell(10,20,'right');assert.equal(await page.locator('#boxSelectBtn').getAttribute('aria-pressed'),'false');checks.push('X and a right click without dragging exit batch mode');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors};await fs.writeFile(path.join(root,'reports/original_bulk_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
