const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1540,height:1060}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BLUEPRINT_TEST_URL||pathToFileURL(path.join(root,'dist/offline/blueprint_defense.html')).href);await page.evaluate(()=>BlueprintDefense.ready);
 async function point(x,y){return page.evaluate(({x,y})=>{const p=BlueprintDefense.screen(x+.5,y+.5),r=document.getElementById('board').getBoundingClientRect();return{x:p.x+r.x,y:p.y+r.y};},{x,y});}
 async function hover(x,y){const p=await point(x,y);await page.mouse.move(p.x,p.y);await page.waitForTimeout(100);}
 async function cell(x,y){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
 async function type(n){await page.locator(`[data-deck-page="${[0,8].includes(n)?3:2}"]`).click();await page.locator(`[data-production-type="${n}"]`).click();}
 const units=()=>page.evaluate(()=>BlueprintDefense.game.production.map(p=>({id:p.id,type:p.type,x:p.x,y:p.y,dir:p.dir,recipe:p.recipe,source:p.source,deliveryMode:p.deliveryMode})));
 async function drag(points,release=true){const first=await point(...points[0]);await page.mouse.move(first.x,first.y);await page.mouse.down();for(const c of points.slice(1)){const p=await point(...c);await page.mouse.move(p.x,p.y,{steps:8});}if(release)await page.mouse.up();await page.waitForTimeout(120);}
 await type(0);await cell(1,43);await type(2);await hover(1,40);assert.match(await page.locator('#placementPreview').textContent(),/已对齐 1 处接口/);await page.screenshot({path:path.join(root,'reports/placement_snap.png')});await cell(1,40);let built=await units();assert.deepEqual([built[1].x,built[1].y,built[1].dir],[1,40,3]);await type(3);await cell(1,37);assert.equal(await page.locator('#dp').textContent(),'2,900');checks.push('three clicks build a directly connected full-size source/refinery/storage line; the requested anchor is kept while its orientation aligns to the source');
 await cell(2,41);await page.locator('#productionOption').selectOption('furnance_quartz_glass_1');await page.locator('#copyBtn').click();assert.equal(await page.locator('#productionOption').inputValue(),'furnance_quartz_glass_1');await cell(5,24);built=await units();assert.equal(built[3].recipe,'furnance_quartz_glass_1');assert.equal(built[3].dir,3);checks.push('copy-build carries the selected production recipe and rotation into a new building without changing the original');
 await cell(2,43);await page.locator('#moveBtn').click();await hover(9,24);await page.keyboard.press('r');await page.waitForTimeout(100);built=await units();assert.deepEqual([built[0].x,built[0].y,built[0].dir],[1,43,3]);assert.match(await page.locator('#detailRole').textContent(),/1×3/);const money=await page.locator('#dp').textContent();await page.screenshot({path:path.join(root,'reports/placement_move_rotation.png')});await cell(9,24);built=await units();assert.deepEqual([built[0].x,built[0].y,built[0].dir],[9,24,0]);assert.equal(await page.locator('#dp').textContent(),money);
 await page.keyboard.press('m');await cell(20,5);assert.match(await page.locator('#status').textContent(),/通道/);assert.deepEqual(await units(),built);await page.keyboard.press('Escape');assert.deepEqual(await units(),built);checks.push('moving rotates only the held preview until confirmation; invalid drops and Escape preserve the original, and a valid move costs nothing');
 await page.locator('#resetBtn').click();await type(2);await cell(12,20);await type(1);await drag([[10,22],[12,22]],false);assert.equal((await units()).length,1);assert(await page.locator('#placementPreview').evaluate(e=>e.classList.contains('invalid')));await page.mouse.up();assert.equal((await units()).length,1);assert.equal(await page.locator('#dp').textContent(),'3,500');assert.match(await page.locator('#status').textContent(),/未扣款/);
 await drag([[10,24],[14,24],[14,23]],false);assert.equal((await units()).length,1);assert.match(await page.locator('#placementPreview').textContent(),/6 格.*600 折金票/);await page.screenshot({path:path.join(root,'reports/placement_belt_preview.png')});await page.mouse.up();built=await units();assert.equal(built.length,7);assert.equal(await page.locator('#dp').textContent(),'2,900');assert.equal(built.find(p=>p.x===14&&p.y===24).dir,3);assert.equal(built.find(p=>p.x===10&&p.y===24).dir,0);checks.push('dragging creates a live L-shaped six-cell preview and commits once; blocked routes spend nothing and build no partial line');
 await drag([[10,24],[12,24]]);assert.equal((await units()).length,7);assert.equal(await page.locator('#dp').textContent(),'2,900');await drag([[25,22],[28,22]],false);await page.keyboard.press('Escape');await page.mouse.up();assert.equal((await units()).length,7);assert.equal(await page.locator('#dp').textContent(),'2,900');checks.push('overdrawing reuses existing belts without charging twice; Escape cancels an unfinished drag');
 await type(2);await hover(10,26);await page.keyboard.press('g');assert.equal(await page.locator('#snapBtn').getAttribute('aria-pressed'),'false');await page.keyboard.press('g');assert.equal(await page.locator('#snapBtn').getAttribute('aria-pressed'),'true');await page.keyboard.down('Alt');await hover(10,26);assert(!/自动对齐/.test(await page.locator('#placementPreview').textContent()));await page.keyboard.up('Alt');checks.push('G and the visible toggle control snapping; holding Alt permits exact free placement');
 await type(1);await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();const cameraBefore=await page.evaluate(()=>BlueprintDefense.camera.cx),p=await point(22,20);await page.mouse.move(p.x,p.y);await page.mouse.down({button:'middle'});await page.mouse.move(p.x+80,p.y+20,{steps:5});await page.mouse.up({button:'middle'});assert.notEqual(await page.evaluate(()=>BlueprintDefense.camera.cx),cameraBefore);assert.equal((await units()).length,7);checks.push('middle-button drag still pans while the belt tool is selected and never lays a belt');
 await page.setViewportSize({width:390,height:844});await page.locator('#zoomReset').click();await type(1);const before=await units(),cdp=await page.context().newCDPSession(page),r=await page.locator('#board').boundingBox(),cx=r.x+r.width/2,cy=r.y+r.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-20,y:cy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-10,y:cy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-10,y:cy,id:1},{x:cx+20,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-50,y:cy,id:1},{x:cx+50,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await units(),before);assert(await page.evaluate(()=>BlueprintDefense.camera.zoom>1));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(root,'reports/placement_phone.png')});checks.push('adding a second touch cancels the draft and pinches to zoom without spending; the phone toolbar fits');
 assert.deepEqual(errors,[]);const report={passed:checks.length,checks,errors};await fs.writeFile(path.join(root,'reports/placement_browser_checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
